### ISSUE TITLE
support for iOS

### ISSUE THREAD

**Issue by pzoltowski** [kosua20/Rendu#5]
Just came a cross this project and I found it very interesting. Do you have idea how hard would be to make it support iOS as well? (at least with some few projects: imageViewer, game controller, etc). Should it be downgraded to opengl 2.0 or rather upgraded to vulkan/metal?

**Comment by kosua20** [comment]
Hello, and thank you :)
I don't know if OpenGLES 3 is widely supported on iOS or not, but you would have to port most of the rendering API and shaders to either GLES or as you mentioned Metal / Vulkan over Metal. Even if this part is done you would still have to get the C++ side of the code running on iOS. You would also probably have to update the code that deals with the windowing system (I'm not sure GLFW supports iOS), and also handle touch inputs instead of mouse+keyboard. So that would be a quite large rewrite I think!

**Comment by pzoltowski** [comment]
Good to know. I guess trying to downgrade shaders to OpenGLES 3 (seems all iphones since iPhone 5S support it). GLFW seems not supported on iOS :( . Maybe will have more luck adopting GLFM instead (https://github.com/brackeen/glfm) - it already handles touch input on both android and iOS devices. Do you have idea how much more advanced features above OpenGLES 3 your library uses? (It's been a while since I touched any kind of OpenGL so I have no clue).

**Comment by kosua20** [comment]
I'm not super familiar with the limitations of GLES3 vs GL4.1. Looking at the wiki page for GLES, I would say the most 'advanced' features Rendu is using are all supported by GLES 3.2:

* floating point formats for framebuffers
* geometry and tessellation shaders
* texture cubemap arrays

I'm not sure any iOS device is supporting 3.2, but they might still support these features through extensions.
Furthermore, these are mainly used in more advanced demos in Rendu, so ControllerConfig or ImageViewer would not necessarily require them.
